Repository Dev-FE-2/toy-project3-team1, pull requests merged in 2025-01, with the labels that each got.

#10 [🎨 HTML&CSS] 공통 컴포넌트 - Header,Navbar
  package-lock.json
  package.json
  src/App.tsx
  src/components/.gitkeep
  src/components/Profile/Profile.styles.ts
  src/components/Profile/Profile.tsx
  src/components/header/header-main/Header.styled.ts
  src/components/header/header-main/Header.tsx
  src/components/header/header-sub/Header.styled.ts
  src/components/header/header-sub/HeaderSub.tsx
  src/components/navbar/Navbar.styled.ts
  src/components/navbar/Navbar.tsx
  src/routes/Router.tsx
  src/styles/common.css
  src/types/.gitkeep
  src/types/button.ts
  src/types/profile.ts
Labels: 🎨 HTML&CSS

#9 [Feature] Toast ui 구현
  src/components/ToastMessage/ToastMessageContainer.tsx
  src/components/ToastMessage/ToastMessageItem.tsx
  src/components/ToastMessage/toastMessage.module.ts
  src/components/ToastMessage/toastMessageContainer.module.ts
  src/main.tsx
  src/providers/ToastMessageProvider.tsx
  src/providers/index.tsx
  src/types/ToastMessage.d.ts
Labels: ✨ Feature

#13 [🎨 HTML&CSS] 공통 컴포넌트 - Feedlist,playlist
  .gitignore
  src/App.tsx
  src/components/DetailPlayList/DetailPlayList.styles.ts
  src/components/DetailPlayList/DetailPlaylist.tsx
  src/components/Feedlist/Feedlist.styles.ts
  src/components/Feedlist/Feedlist.tsx
  src/components/Feedlist/Footer.tsx
  src/components/Playlist/Footer.tsx
  src/components/Playlist/Playlist.styles.ts
  src/components/Playlist/Playlist.tsx
  src/pages/Home.tsx
  src/types/List.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: 🎨 HTML&CSS

#23 [⚙️ Setting] supabase 세팅 , husky 수정(2)
  .commitlintrc.json
  .github/pull_request_template.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  eslint.config.js
  package-lock.json
  package.json
  supabaseConfig.ts
  tsconfig.app.tsbuildinfo
  types_db.ts
Labels: ⚙ Setting

#20 [🎨 HTML&CSS] Button,Profile 추가 및 header수정
  src/components/Profile/Profile.styles.ts
  src/components/button/Button.styles.ts
  src/components/button/Button.tsx
  src/components/header/header-main/Header.styled.ts
  src/components/header/header-sub/Header.styled.ts
  src/components/header/header-sub/HeaderSub.tsx
  src/types/button.ts
Labels: 🎨 HTML&CSS

#12 [HTML&CSS] 모달 제작 #11
  index.html
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalFull.tsx
  src/hooks/.gitkeep
  src/hooks/useScrollLock.ts
  src/styles/modal/modal.style.ts
  src/styles/modal/modalfull.style.ts
  src/types/modal.ts
Labels: 🎨 HTML&CSS

#29 [✨ Feature] Layout 구조 작성
  src/App.tsx
  src/components/Layout/Layout.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalFull.tsx
  src/routes/Router.tsx
  src/styles/common.css
  tsconfig.app.tsbuildinfo
Labels: ✨ Feature

#26 [🐛 Bug] vite 환경변수
  src/vite-env.d.ts
  supabaseConfig.ts
  tsconfig.app.json
  tsconfig.app.tsbuildinfo
  tsconfig.node.json
  vite-env.d.ts
Labels: 🔧 BugFix

#31 [✨ Feature] 라우터 작업
  src/pages/Home.tsx
  src/pages/index.ts
  src/pages/login/index.tsx
  src/pages/myPlayList/index.tsx
  src/pages/mypage/index.tsx
  src/pages/notfound/index.tsx
  src/pages/playListCreate/index.tsx
  src/pages/profileEdit/index.tsx
  src/pages/signup/index.tsx
  src/pages/subscriptions/index.tsx
  src/pages/userProfile/index.tsx
  src/pages/view/index.tsx
  src/routes/Router.tsx
  tsconfig.app.tsbuildinfo
Labels: ✨ Feature

#38 [FEAT] Modal 스타일 수정, open기능 추가 #37
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalFull.tsx
  src/components/Modal/modal.style.ts
  src/components/Modal/modalfull.style.ts
  src/types/modal.ts
Labels: ✨ Feature, 🎨 HTML&CSS

#34 [🎨 HTML&CSS] 메인피드 마크업
  package-lock.json
  package.json
  src/apis/.gitkeep
  src/apis/axiosInstance.ts
  src/components/Feedlist/Feedlist.styles.ts
  src/components/Feedlist/Feedlist.tsx
  src/pages/Home.tsx
  src/pages/index.ts
  src/types/List.ts
  tsconfig.app.tsbuildinfo
Labels: 🎨 HTML&CSS

#42 [🎨 HTML&CSS] 플레이 리스트 상세 페이지 UI 작업 #41
  src/components/Comment/CommentEditor.tsx
  src/components/Comment/CommentItem.tsx
  src/components/Comment/CommentList.tsx
  src/components/DetailPlayList/DetailPlayList.styles.ts
  src/components/Input/Input.tsx
  src/components/Textarea/Textarea.tsx
  src/components/ViewVideoList/ViewVideoList.style.ts
  src/components/ViewVideoList/ViewVideoList.tsx
  src/pages/view/index.tsx
  src/styles/common.css
  src/styles/components/comment/comment-editor.style.ts
  src/styles/components/comment/comment-item.style.ts
  src/styles/components/comment/comment-list.style.ts
  src/styles/pages/view/view.style.ts
  src/types/View.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ Feature, 🎨 HTML&CSS

#45 [✨ Feature] 로그인 정보저장
  package-lock.json
  src/pages/login/index.tsx
Labels: ✨ Feature

#48 [🐛 Bug] List 대소문자 에러수정
  src/components/Comment/CommentList.tsx
  src/components/Playlist/Playlist.styles.ts
  src/components/Playlist/Playlist.tsx
  src/components/ViewVideoList/ViewVideoList.style.ts
  src/components/ViewVideoList/ViewVideoList.tsx
  src/pages/Home.tsx
  src/pages/index.ts
  src/pages/myPlayList/index.tsx
  src/pages/playListCreate/index.tsx
  src/pages/view/index.tsx
  src/routes/Router.tsx
  src/styles/pages/view/view.style.ts
  src/types/View.ts
  tsconfig.app.tsbuildinfo
Labels: 🔧 BugFix

#39 [✨ Feature] 구독 목록 페이지 마크업 및 구독 목록 드래그 스크롤 기능 구현
  src/assets/test.webp
  src/components/SubscribeList/SubscribeList.module.ts
  src/components/SubscribeList/SubscribeList.tsx
  src/hooks/useDragScroll.tsx
  src/pages/subscriptions/index.tsx
  src/routes/Router.tsx
  tsconfig.app.tsbuildinfo
Labels: ✨ Feature, 🎨 HTML&CSS

#51 [🔄 Refactor] 레이아웃 수정 #47
  src/components/Layout/Layout.tsx
  src/components/header/header-main/Header.styled.ts
  src/components/header/header-main/Header.tsx
  src/components/header/header-sub/Header.styled.ts
  src/components/header/header-sub/HeaderSub.tsx
  src/components/navbar/Navbar.styled.ts
  src/components/navbar/Navbar.tsx
  src/constants/constant.ts
  src/routes/Router.tsx
  src/styles/common.css
Labels: 🔄 Refactor

#56 [⚙️ Setting] tanstack query 세팅 #54
  package-lock.json
  package.json
  src/components/Layout/Layout.tsx
Labels: ⚙ Setting

#55 [⚙️ Setting] husky build,git index설정
  .husky/pre-commit
  src/components/Comment/CommentList.tsx
  src/components/DetailPlayList/DetailPlayList.tsx
  src/components/FeedList/FeedList.styles.ts
  src/components/FeedList/FeedList.tsx
  src/components/FeedList/Footer.tsx
  src/components/PlayList/Footer.tsx
  src/components/PlayList/PlayList.module.ts
  src/components/PlayList/PlayList.styles.ts
  src/components/PlayList/PlayList.tsx
  src/components/PlayList/PlayListSkeleton.tsx
  src/pages/login/login.styles.ts
  src/pages/notFound/index.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: ⚙ Setting

#50 [🎨 HTML&CSS] 플레이리스트 생성페이지 마크업
  package-lock.json
  src/components/button/Button.styles.ts
  src/components/button/Button.tsx
  src/components/playListCreate/PlayListCreate.styles.ts
  src/components/playListCreate/PlayListInfo.tsx
  src/components/playListCreate/PlayListIsPublic.tsx
  src/hooks/useDebounce.ts
  src/hooks/useImageUpload.ts
  src/hooks/useVideoLink.ts
  src/pages/index.ts
  src/pages/login/login.styles.ts
  src/pages/playListCreate/index.tsx
  src/styles/components/comment/comment-List.style.ts
  src/types/playListCreate.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.json
Labels: ✨ Feature

#63 [✨ Feature] 로그인 정보 저장
  src/components/Profile/Profile.styles.ts
  src/components/navbar/Navbar.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/store/useAuthStore.ts
  src/utils/authUtils.ts
  src/utils/checkLoginStatus.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ Feature

#67 [✨ Feature] feed 관련 optionpopup 만들기
  src/components/Feedlist/Feedlist.styles.ts
  src/components/Feedlist/Feedlist.tsx
  src/components/Feedlist/Footer.tsx
  src/components/Layout/Layout.tsx
  src/components/ViewVideoList/ViewVideoList.tsx
  src/hooks/useCheckLoginStatus.ts
  src/pages/Home.tsx
  src/pages/index.ts
  src/pages/playListCreate/index.tsx
  src/store/useAuthStore.ts
  src/utils/authUtils.ts
  tsconfig.app.json
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: ✨ Feature

#68 [🎨 HTML&CSS] 회원가입
  .husky/pre-commit
  src/components/Button/Button.styles.ts
  src/components/Feedlist/Footer.tsx
  src/components/Layout/Layout.tsx
  src/components/SignUp/SignUp.styles.ts
  src/components/SignUp/StepEmail.tsx
  src/components/SignUp/StepNickname.tsx
  src/components/SignUp/StepPassword.tsx
  src/components/button/Button.styles.ts
  src/constants/constant.ts
  src/hooks/useEmailCheck.ts
  src/pages/login/index.tsx
  src/pages/login/login.styles.ts
  src/pages/playListCreate/index.tsx
  src/pages/signup/index.tsx
  src/routes/Router.tsx
  src/schema/signupSchema.ts
  src/store/signupStore.ts
  src/styles/common.css
Labels: ✨ Feature, 🎨 HTML&CSS

#70 [✨ Feature] 메인 피드 데이터베이스 데이터 가져오기
  src/apis/axiosInstance.ts
  src/apis/feed/index.ts
  src/components/FeedList/Feedlist.style.ts
  src/components/Feedlist/Feedlist.tsx
  src/components/Feedlist/Footer.tsx
  src/components/Layout/Layout.tsx
  src/components/Skeleton/PlayListSkeleton.module.ts
  src/components/Skeleton/PlayListSkeleton.tsx
  src/hooks/useInfiniteScroll.tsx
  src/pages/Home.tsx
  src/repository/authRepository.ts
  src/styles/GlobalStyles.ts
  src/types/List.ts
  src/types/playList.ts
  src/utils/.gitkeep
  src/utils/dateKoreanFormat.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ Feature

#73 [🎨 HTML&CSS] 공통 컴포넌트 - confirm modal
  package-lock.json
  package.json
  src/components/ConfirmModal/ConfirmModal.styles.ts
  src/components/ConfirmModal/ConfirmModal.tsx
  src/components/DetailPlayList/DetailPlayList.tsx
  src/components/Feedlist/FeedList.tsx
  src/components/PlayList/PlayList.styles.ts
  src/components/PlayList/PlayList.tsx
  src/components/ViewVideoList/ViewVideoList.tsx
  src/hooks/useModal.tsx
  src/pages/login/index.tsx
  src/pages/playListCreate/index.tsx
  src/providers/index.tsx
  src/store/useAuthStore.ts
  src/types/modal.ts
  tsconfig.app.tsbuildinfo
Labels: 🎨 HTML&CSS

#86 [✨ Feature] 구글로그인, 생성페이지 api변경, tanstack query적용
  package-lock.json
  package.json
  src/assets/img/login/google.svg
  src/assets/img/login/kakao.svg
  src/components/Button/Button.styles.ts
  src/components/FeedList/FeedList.style.ts
  src/components/FeedList/Footer.tsx
  src/components/PlayList/Footer.tsx
  src/components/SignOut/SignOutButton.tsx
  src/components/SignUp/StepNickname.tsx
  src/components/button/Button.styles.ts
  src/hooks/useCheckLoginStatus.ts
  src/hooks/useEmailCheck.ts
  src/pages/Login/index.tsx
  src/pages/Login/login.styles.ts
  src/pages/index.ts
  src/pages/login/index.tsx
  src/pages/login/login.styles.ts
  src/pages/mypage/Mypage.styled.ts
  src/pages/notFound/index.tsx
  src/pages/playListCreate/index.tsx
  src/store/useAuthStore.ts
  src/supabase/supabaseConfig.ts
  src/types/playListCreate.ts
  src/types/user.ts
  src/utils/refreshAccessToken.ts
  tsconfig.app.json
Labels: ✨ Feature

#87 [✨ Feature] 검색어 기능 구현 및 검색 페이지 구현
  src/apis/axiosInstance.ts
  src/apis/search/index.ts
  src/apis/search/playList/index.ts
  src/components/Layout/Layout.module.ts
  src/components/Layout/Layout.tsx
  src/components/Modal/ModalFull.tsx
  src/components/header/header-main/Header.tsx
  src/components/header/header-sub/HeaderSub.tsx
  src/constants/constant.ts
  src/main.tsx
  src/pages/Home.tsx
  src/pages/index.ts
  src/pages/search/index.tsx
  src/routes/Router.tsx
  src/store/useSearchTermStore.ts
  src/types/playList.ts
Labels: ✨ Feature

#94 [✨ Feature] 플레이리스트 조회,삭제
  src/apis/userInfoApi.ts
  src/components/MyPageType/MyPageLikes.styled.ts
  src/components/MyPageType/MyPageLikes.tsx
  src/components/MyPageType/MyPageSave.tsx
  src/components/Navbar/Navbar.tsx
  src/components/PlayList/PlayList.tsx
  src/components/Profile/Profile.tsx
  src/components/navbar/Navbar.tsx
  src/pages/mypage/index.tsx
  src/pages/profileEdit/index.tsx
  src/store/useAuthStore.ts
  src/types/List.ts
  src/types/profile.ts
Labels: ✨ Feature

#96 [✨ Feature] 나의플레이리스트 페이지 구현
  src/components/Feedlist/FeedList.style.ts
  src/components/MyPlayList/MyPlayList.styles.ts
  src/components/PlayList/PlayList.styles.ts
  src/components/PlayList/PlayList.tsx
  src/components/SignOut/SignOutButton.tsx
  src/hooks/usePlayListOptions.tsx
  src/hooks/useToast.ts
  src/pages/Home.tsx
  src/pages/Login/index.tsx
  src/pages/myPlayList/index.tsx
  src/pages/mypage/index.tsx
  src/pages/notFound/index.tsx
  src/pages/playListCreate/index.tsx
  src/routes/Router.tsx
  src/types/List.ts
Labels: ✨ Feature

#104 [🔄 Refactor] 에러바운더리 , 코드리팩토링
  src/apis/axiosInstance.ts
  src/apis/createPlayList/index.ts
  src/component/ErrorBoundary/ErrorFallback.styles.ts
  src/component/ErrorBoundary/ErrorFallback.tsx
  src/component/Modal/modal.style.ts
  src/component/MyPageType/MyPageLikes.tsx
  src/component/MyPageType/MyPageSave.tsx
  src/component/MyPlayList/MyPlayList.styles.ts
  src/component/PlayList/PlayList.styles.ts
  src/component/PlayList/PlayList.tsx
  src/component/PlayListCreate/PlayListCreate.styles.ts
  src/component/PlayListCreate/PlayListInfo.tsx
  src/component/PlayListCreate/PlayListIsPublic.tsx
  src/component/PlayListCreate/VideoList.tsx
  src/component/SignOut/SignOutButton.tsx
  src/component/SignUp/StepNickname.tsx
  src/component/SignUp/StepPassword.tsx
  src/component/SubscribeList/SubscriptionListModal.tsx
  src/component/Textarea/Textarea.tsx
  src/hooks/useMyPlayListOptions.tsx
  src/main.tsx
  src/pages/index.ts
  src/pages/login/login.styles.ts
  src/pages/playListCreate/index.tsx
  src/pages/profileEdit/index.tsx
  src/pages/signIn/index.tsx
  src/pages/signIn/signIn.styles.ts
  src/routes/Router.tsx
  src/styles/GlobalStyles.ts
  src/supabase/supabaseConfig.ts
  src/utils/writingHashtags.tsx
Labels: 🎨 HTML&CSS, 🔄 Refactor

#108 [🔄 Refactor] store update 이슈
  package-lock.json
  package.json
  src/apis/userInfoApi.ts
  src/pages/mypage/index.tsx
  src/pages/profileEdit/index.tsx
  src/types/profileEdit.ts
Labels: 🔄 Refactor

#116 [🔄 Refactor] 프로필 수정 기본값 새로고침시 사라지는 것 해결
  src/component/Navbar/Navbar.tsx
  src/pages/profileEdit/index.tsx
  src/store/useAuthStore.ts
  src/types/profileEdit.ts
Labels: 🔄 Refactor

#133 [⚙️ Setting] Playwright 세팅
  .gitignore
  e2e/tests-examples/demo-todo-app.spec.ts
  e2e/tests/example.spec.ts
  package-lock.json
  package.json
  playwright.config.ts
  tsconfig.node.json
Labels: ⚙ Setting

#130 [🐛 Bug] 내 플레이리스트 삭제 실패 이슈
  src/component/ErrorBoundary/ErrorFallback.tsx
  src/component/Input/Input.tsx
  src/component/MyPlayList/MyPlayList.styles.ts
  src/component/PlayListCreate/PlayListCreate.styles.ts
  src/pages/view/index.tsx
  src/utils/writingHashtags.tsx
Labels: 🔧 BugFix

#131 [🐛 Bug] 마이페이지 저장 삭제시 전체 다 삭제되는 이슈 #121
  src/apis/userInfoApi.ts
  src/component/MyPageType/MyPageSave.tsx
  src/component/PlayList/PlayList.styles.ts
  src/component/PlayList/PlayList.tsx
  src/types/List.ts
Labels: 🔧 BugFix

#140 feat: 세팅 수정
  playwright.config.ts
Labels: ⚙ Setting

#128 [🐛 Bug] 플리 상세페이지에서 댓글 수가 실시간으로 반영되지 않는 이슈 #120
  src/hooks/useDeleteComment.ts
Labels: 🔧 BugFix

#143 [🐛 Bug] 프로필 수정시 최신 이미지 업데이트 store에 반영 안되는 이슈
  src/pages/profileEdit/index.tsx
Labels: 🔧 BugFix

#135 [🐛 Bug] 구독한 사람이 없으면 구독한사람이 없다고 처리 및 검색한 내용 없습니다 처리
  src/component/SubscribeList/SubscribeList.tsx
  src/component/SubscribeList/SubscriptionListModal.tsx
  src/pages/search/index.tsx
Labels: 🔧 BugFix

#134 [🐛 Bug] popup toast message 및 팝업 창 닫기
  src/apis/search/playList/index.ts
  src/component/FeedList/FeedList.tsx
  src/component/FeedList/FeedListOptionPopUp.tsx
  src/component/ToastMessage/toastMessageContainer.module.ts
  src/pages/search/index.tsx
Labels: 🔧 BugFix

#136 [🐛 Bug] 공개여부에 따라 플리 보여주기
  src/apis/feed/index.ts
  src/apis/search/playList/index.ts
  src/component/FeedList/FeedList.tsx
  src/component/SubscribeList/AllSubscribePlayLists.tsx
  src/component/SubscribeList/SubscribePlayLists.tsx
  src/pages/Home.tsx
  src/pages/search/index.tsx
  src/types/List.ts
Labels: 🔧 BugFix

#138 [🐛 Bug] 플레이리스트 클릭 시 상세 플리로 이동
  src/component/FeedList/FeedList.style.ts
  src/component/FeedList/FeedList.tsx
  src/types/List.ts
Labels: 🔧 BugFix

#139 [🐛 Bug] 피드 리스트에서 프로필 누를 시 상세 프로필 페이지로 이동 처리
  src/component/FeedList/FeedList.style.ts
  src/component/FeedList/FeedList.tsx
Labels: 🔧 BugFix

#141 [🐛 Bug] 무한 스크롤 이미지 깜빡임 처리
  src/apis/feed/index.ts
  src/apis/search/playList/index.ts
  src/apis/subscribe/playList/index.ts
  src/apis/subscribe/subscribePlayList/index.ts
  src/component/FeedList/FeedList.style.ts
  src/component/SubscribeList/AllSubscribePlayLists.tsx
  src/component/SubscribeList/SubscribePlayLists.tsx
  src/component/index.ts
  src/pages/Home.tsx
  src/pages/search/index.tsx
Labels: 🔧 BugFix

#156 [🐛 Bug] 좋아요,저장 즉시 반영 안되는 문제 수정
  src/component/MyPageType/MyPageLikes.tsx
  src/component/MyPageType/MyPageSave.tsx
Labels: 🔧 BugFix

#157 [🎨 HTML&CSS] 피드 아이템 비율 수정
  src/component/FeedList/FeedList.style.ts
Labels: 🎨 HTML&CSS

#152 [✨ Feature] auth playwright 테스트
  .gitignore
  e2e/tests/signin.spec.ts
  e2e/tests/signup.spec.ts
  playwright.config.ts
  src/component/SignUp/StepEmail.tsx
  src/pages/signIn/index.tsx
Labels: ✨ Feature

#154 [🐛 Bug] 소셜로그인 시 토스트, 비로그인 검사
  src/main.tsx
  src/pages/signIn/index.tsx
  src/routes/Router.tsx
Labels: 🔧 BugFix

#146 [🐛 Bug] 검색페이지에서 플리 옵션이 기능 작동이 안되는 오류 수정
  src/apis/search/index.ts
  src/apis/search/playList/index.ts
  src/component/Layout/Layout.tsx
  src/component/Modal/ModalFull.tsx
  src/component/Search/SearchList.tsx
  src/pages/Home.tsx
  src/pages/search/index.tsx
Labels: 🔧 BugFix

#165 [🐛 Bug] 구독 정보가 구독 피드 페이지에서 바로 반영되지 않는 문제 및 팝업 url 초기화
  src/component/FeedList/FeedList.style.ts
  src/component/FeedList/FeedList.tsx
  src/component/FeedList/FeedListOptionPopUp.tsx
  src/component/FeedList/Footer.tsx
  src/component/Search/SearchList.tsx
  src/component/SubscribeList/AllSubscribePlayLists.tsx
  src/component/SubscribeList/SubscribeList.tsx
  src/component/SubscribeList/SubscribePlayLists.tsx
  src/component/SubscribeList/SubscriptionListModal.tsx
  src/component/ViewVideoList/ViewVideoList.tsx
  src/pages/Home.tsx
  src/pages/search/index.tsx
  src/routes/Router.tsx
Labels: 🔧 BugFix

#168 [🐛 Bug] 댓글 수정시 토스트 안뜨는 이슈
  src/component/Comment/CommentModifier.tsx
Labels: 🔧 BugFix

#169 [🐛 Bug] 구독 목록 List css 수정
  src/component/Modal/ModalFull.tsx
  src/component/Search/SearchList.tsx
  src/component/SubscribeList/SubscribeList.module.ts
  src/component/SubscribeList/SubscriptionListModal.tsx
  src/component/header/header-main/Header.tsx
  src/component/header/header-sub/HeaderSub.tsx
  src/pages/search/index.tsx
Labels: 🔧 BugFix

#177 [🔄 Refactor] supabaseAPI axios로 변환
  src/apis/bookmark/deleteUserBookmarkPlayList/index.ts
  src/apis/bookmark/fetchUserBookmarkPlayList/index.ts
  src/apis/like/deleteProfileListPlaylist/index.ts
  src/apis/like/fetchProfileLikePlayList/index.ts
  src/apis/profileEdit/index.ts
  src/apis/user/fetchUserDataType/index.ts
  src/apis/user/fetchUserPlayList/index.ts
  src/apis/userInfoApi.ts
  src/component/MyPageType/MyPageLikes.tsx
  src/component/MyPageType/MyPageSave.tsx
  src/component/MyPageType/UserProfileList.tsx
  src/hooks/useUserInfo.ts
  src/pages/mypage/index.tsx
  src/pages/profileEdit/index.tsx
  src/pages/userProfile/index.tsx
Labels: 🔄 Refactor

#181 [🔄 Refactor] React Profiler를 이용하여 성능 최적화
  src/component/FeedList/FeedList.tsx
  src/component/FeedList/FeedListOptionPopUp.tsx
  src/component/Search/SearchList.tsx
  src/component/SubscribeList/SubscribeList.tsx
  src/component/SubscribeList/SubscriptionListModal.tsx
  src/pages/search/index.tsx
Labels: 🔄 Refactor

#182 [🔄 Refactor] api코드 수정, 컴포넌트 분리
  src/apis/myPlayList/index.ts
  src/apis/signup/index.ts
  src/component/Navbar/Navbar.styled.ts
  src/component/Navbar/Navbar.tsx
  src/component/SignUp/StepEmail.tsx
  src/hooks/useEmailCheck.ts
  src/hooks/useMyPlayList.ts
  src/pages/myPlayList/index.tsx
  src/pages/playListCreate/index.tsx
Labels: 🔄 Refactor
